config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :company_layouts
  end

  get '/' => 'company/home#index', :constraints => { :subdomain => /.+/ }
  constraints DomainConstraint.new('textile.com') do
    root :to => 'home#index', :as => :home
  end
  root :to => "company/home#index", :as => :company_home
  
  
  devise_for :users, :controllers => { :sessions => 'sessions', :registrations => 'registrations', :passwords => 'passwords' }
  
  resources :users
  
  get '/admin' => 'admin/home#index', :as => :admin_home
  namespace :admin do
    resources :categories, :markets, :work_types, :contact_us, :products, :companies, :users, :company_layouts
    resources :albums do
      resources :album_products
    end
    #resources :albums do
     # collection do
      #  get :products
      #end
    #end
  end
  
  namespace :company do
		resources :albums
    namespace :admin do
      resources :contact_us, :products, :companies, :company_layouts
      get '/home' => 'home#index', :as => :home
      resources :company_work_types do
        get :autocomplete_work_type_name, :on => :collection
      end
      resources :albums do
        resources :album_products
      end      
    end
    get '/photos/:type/:id' => 'home#photos', :as => :photos
  end
  
  #get '/albums' => 'company/albums#index', :as => :albums
  
  get '/company_not_found' => 'no_company#company_not_found', :as => :company_not_found
  post '/contact_us_save' => 'home#contact_us_save', :as => :contact_us_save
  
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::AdminApplicationController  
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.order(sort_column(params[:sort]) + " " + sort_direction(params[:direction])).paginate(:per_page => PER_PAGE, :page => params[:page])
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
    #1.times { @product.company_work_types.build }
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        @company.work_types.destroy_all
        params[:company_work_type][:work_type_id].each do |work_type|
          @company.company_work_types.create(:work_type_id => work_type)
        end        
        format.html { redirect_to admin_companies_url, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        @company.work_types.destroy_all
        params[:company_work_type][:work_type_id].each do |work_type|
          @company.company_work_types.create(:work_type_id => work_type)
        end        
        format.html { redirect_to admin_companies_url, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit!
    end
end

app/controllers/company/admin/album_products_controller.rb
class Company::Admin::AlbumProductsController < Company::Admin::CompanyAdminApplicationController  
  before_action :set_album_product, only: [:show, :edit, :update, :destroy]
  
  before_action :set_album

  # GET /admin/album_products
  # GET /admin/album_products.json
  def index
    @album_products = AlbumProduct.includes(:product, :album).order(sort_column(params[:sort]) + " " + sort_direction(params[:direction])).paginate(:per_page => PER_PAGE, :page => params[:page])
    @album_product = AlbumProduct.new
  end

  # GET /admin/album_products/1
  # GET /admin/album_products/1.json
  def show
  end

  # GET /admin/album_products/new
  def new
    @album_product = AlbumProduct.new
  end

  # GET /admin/album_products/1/edit
  def edit
  end

  # POST /admin/album_products
  # POST /admin/album_products.json
  def create
    @album_product = AlbumProduct.new(album_product_params)
    @album_products = AlbumProduct.includes(:product, :album).order(sort_column(params[:sort]) + " " + sort_direction(params[:direction])).paginate(:per_page => PER_PAGE, :page => params[:page])
    respond_to do |format|
      if @album_product.save
        @album_product = AlbumProduct.new
        format.html {  render action: 'index', notice: 'Album product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album_product }
      else
        format.html { render action: 'index' }
        format.json { render json: @album_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/album_products/1
  # PATCH/PUT /admin/album_products/1.json
  def update
    respond_to do |format|
      if @album_product.update(album_product_params)
        format.html {  render action: 'edit', notice: 'Album product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/album_products/1
  # DELETE /admin/album_products/1.json
  def destroy
    @album_product.destroy
    respond_to do |format|
      format.html { redirect_to company_admin_album_album_products_url(@album), notice: 'Album product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album_product
      @album_product = AlbumProduct.find(params[:id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.includes(:company).find(params[:album_id])
    end    

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_product_params
      params.require(:album_product).permit(:album_id, :product_id)
    end
end

app/controllers/company/admin/albums_controller.rb
class Company::Admin::AlbumsController < Company::Admin::CompanyAdminApplicationController  
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /admin/albums
  # GET /admin/albums.json
  def index
    @albums = @current_company.albums.includes(:company).order(sort_column(params[:sort]) + " " + sort_direction(params[:direction])).paginate(:per_page => PER_PAGE, :page => params[:page])
  end

  # GET /admin/albums/1
  # GET /admin/albums/1.json
  def show
  end

  # GET /admin/albums/new
  def new
    @album = Album.new
  end

  # GET /admin/albums/1/edit
  def edit
  end

  # POST /admin/albums
  # POST /admin/albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to company_admin_albums_url, notice: 'Album was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album }
      else
        format.html { render action: 'new' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/albums/1
  # PATCH/PUT /admin/albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to company_admin_albums_url, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/albums/1
  # DELETE /admin/albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to company_admin_albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:company_id, :name, :description, :code, :is_active)
    end
end

app/controllers/company/admin/companies_controller.rb
class Company::Admin::CompaniesController < Company::Admin::CompanyAdminApplicationController  
  before_action :set_company, only: [:edit, :update]

  # GET /companies/1/edit
  def edit
    #@company.company_work_types.build
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to edit_company_admin_company_path(@company), notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit!
    end
end

app/controllers/company/admin/company_admin_application_controller.rb
class Company::Admin::CompanyAdminApplicationController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  PER_PAGE = 10
  
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  
  helper_method :sort_column, :sort_direction
  
  before_action :company_subdomain, :current_company
  helper_method :company_address, :company_mobiles, :company_phones, :current_company

  layout 'admin'
  
  def current_company
    @current_company ||= Company.includes(:market, :products).find_by_custom_domain(request.host) || Company.includes(:market, :products).find_by_sub_domain(current_subdomain)
  end
  
  def company_address
    cmp_add = []
    cmp_add << @current_company.address
    if @current_company.market
      cmp_add << @current_company.market.name
      cmp_add << @current_company.market.area
      cmp_add << @current_company.market.city
      cmp_add << @current_company.market.pincode
    end
    cmp_add.delete_if(&:blank?).join(', ')
  end
  
  def company_mobiles
    cmp_mobiles = []
    cmp_mobiles << @current_company.mobile_1 << @current_company.mobile_2 << @current_company.mobile_3
    cmp_mobiles.delete_if(&:blank?).join(', ')    
  end
  
  def company_phones
    cmp_phones = []
    cmp_phones << @current_company.phone_1 << @current_company.phone_2 << @current_company.phone_3
    cmp_phones.delete_if(&:blank?).join(', ')
  end  
  
  def company_subdomain
    if current_subdomain and current_company.nil?
        redirect_to company_not_found_path
    end
  end  
  
  def sort_column(sort='')
    controller_name.classify.constantize.column_names.include?(sort) ? sort : "id"
  end

  def sort_direction(direction='')
    %w[asc desc].include?(direction) ? direction : "desc"
  end  

end

app/controllers/company/admin/company_layouts_controller.rb
class Company::Admin::CompanyLayoutsController < Company::Admin::CompanyAdminApplicationController
  before_action :set_company_layout, only: [:edit, :update]

  # GET /admin/company_layouts/1/edit
  def edit
  end

  # PATCH/PUT /admin/company_layouts/1
  # PATCH/PUT /admin/company_layouts/1.json
  def update
    respond_to do |format|
      if @company_layout.update(company_layout_params)
        format.html { redirect_to edit_company_admin_company_layout_path(@company_layout), notice: 'Company layout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company_layout.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_layout
      @company_layout = CompanyLayout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_layout_params
      params.require(:company_layout).permit!
    end
end

app/controllers/company/admin/company_work_types_controller.rb
class Company::Admin::CompanyWorkTypesController < Company::Admin::CompanyAdminApplicationController  
  before_action :set_company_work_type, only: [:show, :edit, :update, :destroy]

  autocomplete :work_type, :name, :full => true

  # GET /company_work_types
  # GET /company_work_types.json
  def index
    @company_work_types = @current_company.company_work_types.order(sort_column(params[:sort]) + " " + sort_direction(params[:direction])).paginate(:per_page => PER_PAGE, :page => params[:page])
  end

  # GET /company_work_types/1
  # GET /company_work_types/1.json
  def show
  end

  # GET /company_work_types/new
  def new
    @company_work_type = CompanyWorkType.new
  end

  # GET /company_work_types/1/edit
  def edit
  end

  # POST /company_work_types
  # POST /company_work_types.json
  def create
    respond_to do |format|
      if params[:work_type_name].present?
        work_type = WorkType.find_or_create_by(name: params[:work_type_name])
        params[:company_work_type][:work_type_id] = work_type.id        
        @company_work_type = CompanyWorkType.new(company_work_type_params)
        if @company_work_type.save
          format.html { redirect_to company_admin_company_work_types_url, notice: 'Company Work Type was successfully created.' }
          format.json { render :show, status: :created, location: @company_work_type }
        else
          format.html { render :new }
          format.json { render json: @company_work_type.errors, status: :unprocessable_entity }
        end
      else
        @company_work_type = CompanyWorkType.new(company_work_type_params)
        format.html { render :new }
        format.json { render json: @company_work_type.errors, status: :unprocessable_entity }        
      end    
    end
  end

  # PATCH/PUT /company_work_types/1
  # PATCH/PUT /company_work_types/1.json
  def update
    respond_to do |format|
      if params[:work_type_name].present?
        work_type = WorkType.find_or_create_by(name: params[:work_type_name])
        params[:company_work_type][:work_type_id] = work_type.id      
        if @company_work_type.update(company_work_type_params)
          format.html { redirect_to company_admin_company_work_types_url, notice: 'Company Work Type was successfully updated.' }
          format.json { render :show, status: :ok, location: @company_work_type }
        else
          format.html { render :edit }
          format.json { render json: @company_work_type.errors, status: :unprocessable_entity }
        end
      else  
        format.html { render :edit }
        format.json { render json: @company_work_type.errors, status: :unprocessable_entity }        
      end  
    end
  end

  # DELETE /company_work_types/1
  # DELETE /company_work_types/1.json
  def destroy
    work_type_id = @company_work_type.work_type_id
    @company_work_type.destroy
    
    #destroy work type if no longer use in company.
    work_type = WorkType.find(work_type_id)
    unless work_type.is_default
      company_work_type = work_type.company_work_types.first
      unless company_work_type
        work_type.destroy
      end
    end
      
    respond_to do |format|
      format.html { redirect_to company_admin_company_work_types_url, notice: 'Company Work Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_work_type
      @company_work_type = CompanyWorkType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_work_type_params
      params.require(:company_work_type).permit!
    end
end

app/controllers/company/admin/home_controller.rb
class Company::Admin::HomeController < Company::Admin::CompanyAdminApplicationController
end

app/controllers/company/albums_controller.rb
class Company::AlbumsController < Company::CompanyApplicationController    
  before_action :set_album, only: [:show]
  
  # GET /admin/albums
  # GET /admin/albums.json
  def index
    @albums = @current_company.albums
  end

  # GET /admin/albums/1
  # GET /admin/albums/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/admin/companies/_form.html.erb
<%= form_for [:admin, @company], :html => {:class => "form-horizontal"} do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   	<div class="form-group">
      <label class="col-sm-2 control-label">Market</label>
			<div class="col-sm-10"><%= f.select :market_id, options_for_select([["Select", ""]] + Market.active.collect {|r| [r.name, r.id]}, (@company.market.id unless @company.market.nil?)), :class => "form-control"  %></div>
   	</div>	    

  <div class="form-group">
      <label class="col-sm-2 control-label">Name</label>
  <div class="col-sm-10"> <%= f.text_field :name, :class => "form-control" %></div>
    </div>
    
  <div class="form-group">
      <label class="col-sm-2 control-label">Description</label>
  <div class="col-sm-10"> <%= f.text_area :description, :class => "form-control" %></div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Address</label>
    <div class="col-sm-10"><%= f.text_area :address, :class => "form-control" %></div>
    </div>           

  <div class="form-group">
      <label class="col-sm-2 control-label">Contact person</label>
   <div class="col-sm-10"> <%= f.text_field :contact_person, :class => "form-control" %></div>
    </div>
  <div class="form-group">
      <label class="col-sm-2 control-label">Mobile 1</label>
  <div class="col-sm-10"> <%= f.text_field :mobile_1, :class => "form-control" %></div>
    </div>

  <div class="form-group">
      <label class="col-sm-2 control-label">Mobile 2</label>
  <div class="col-sm-10"> <%= f.text_field :mobile_2, :class => "form-control" %></div>
    </div>
    
  <div class="form-group">
      <label class="col-sm-2 control-label">Mobile 3</label>
    <div class="col-sm-10"><%= f.text_field :mobile_3, :class => "form-control" %></div>
    </div>
    
  <div class="form-group">
      <label class="col-sm-2 control-label">Phone 1</label>
   <div class="col-sm-10"><%= f.text_field :phone_1, :class => "form-control" %></div>
    </div>
    
  <div class="form-group">
      <label class="col-sm-2 control-label">Phone 2</label>
   <div class="col-sm-10"> <%= f.text_field :phone_2, :class => "form-control" %></div>
    </div>
    
  <div class="form-group">
      <label class="col-sm-2 control-label">Phone 3</label>
    <div class="col-sm-10"><%= f.text_field :phone_3, :class => "form-control" %></div>
    </div>
    
  <div class="form-group">
      <label class="col-sm-2 control-label">What I Do Lable</label>
    <div class="col-sm-10"><%= f.text_field :what_i_do_label, :class => "form-control" %></div>
    </div>

  <div class="form-group">
      <label class="col-sm-2 control-label">What I Do Desc</label>
    <div class="col-sm-10"><%= f.text_area :what_i_do_desc, :class => "form-control" %></div>
    </div>           
    
  <div class="form-group">
      <label class="col-sm-2 control-label">Who I Am Label</label>
  <div class="col-sm-10">  <%= f.text_field :who_i_am_label, :class => "form-control" %></div>
    </div>

  <div class="form-group">
      <label class="col-sm-2 control-label">Who I Am Desc</label>
   <div class="col-sm-10"> <%= f.text_area :who_i_am_desc, :class => "form-control" %></div>
    </div>
    
  <div class="form-group">
      <label class="col-sm-2 control-label">My Work Label</label>
   <div class="col-sm-10"> <%= f.text_field :my_work_label, :class => "form-control" %></div>
    </div>
    
  <div class="form-group">
      <label class="col-sm-2 control-label">My Work Desc</label>
    <div class="col-sm-10"><%= f.text_area :my_work_desc, :class => "form-control" %></div>
    </div>           
    
  <div class="form-group">
      <label class="col-sm-2 control-label">Footer Content</label>
    <div class="col-sm-10"><%= f.text_field :footer_content, :class => "form-control" %></div>
    </div>           
    
  <div class="form-group">
      <label class="col-sm-2 control-label">Work Types</label>
		<div class="col-sm-10"><%= select_tag "company_work_type[work_type_id]", options_for_select([["Select", ""]] + WorkType.active.collect {|r| [r.name, r.id]}, @company.work_types.map{|work_type| work_type.id}), :multiple => true %></div>
		<%= hidden_field "company_work_type[company_id]", @company.id %>
    </div>     
    
   <div class="checkbox">
      <label class="col-sm-2 control-label"></label>
      <label><%= f.check_box :is_active %> Active</label>
   </div>        
    
  <div class="form-group">
      <label class="col-sm-2 control-label">Logo</label>
    <div class="col-sm-10"><%= f.file_field :logo, :class => "form-control" %></div>
    </div>   
     
  <div class="form-group">
  	<label class="col-sm-2 control-label"></label>
    <div class="col-sm-10"><%= image_tag(@company.logo_url) if @company.logo.present? %></div>
    </div>     
    
  <div class="form-group">
      <label class="col-sm-2 control-label">Favicon</label>
    <div class="col-sm-10"><%= f.file_field :favicon, :class => "form-control" %></div>
    </div>   
     
  <div class="form-group">
  	<label class="col-sm-2 control-label"></label>
    <div class="col-sm-10"><%= image_tag(@company.original_url) if @company.favicon.present? %></div>
    </div>        

  <div class="form-group">
  	<div class="col-sm-offset-2 col-sm-10">
  		<%= link_to 'Back', admin_companies_path, :class => "btn-primary btn" %>
    	<%= f.submit  :class => "btn-success btn" %>
    </div>	
  </div>

<% end %>

app/views/admin/companies/edit.html.erb
<h3 class="alert alert-info">Edit</h3>

<%= render 'form' %>

app/views/admin/companies/index.html.erb
<h3 class="alert alert-info">Listing companies <div class="right mt3"><%= link_to 'New Company', new_admin_company_path, :class => "btn-primary btn" %></div></h3>
<div class="table-responsive">
	<table class="table table-hover table-condensed">
  <thead>
    <tr>
    	<th><%= sortable "name", t("general.name") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
      	<td><%= company.name %></td>
        <td><%= link_to 'Edit', edit_admin_company_path(company), :class => "btn-success btn" %>
        <%= link_to 'Destroy', [:admin, company], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn-danger btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<div class="right"><%= will_paginate @companies %></div>
</div>

app/views/admin/companies/new.html.erb
<h3 class="alert alert-info">Add</h3>

<%= render 'form' %>