config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :company_layouts
  end

  get '/' => 'company/home#index', :constraints => { :subdomain => /.+/ }
  constraints DomainConstraint.new('textile.com') do
    root :to => 'home#index', :as => :home
  end
  root :to => "company/home#index", :as => :company_home
  
  
  devise_for :users, :controllers => { :sessions => 'sessions', :registrations => 'registrations', :passwords => 'passwords' }
  
  resources :users
  
  get '/admin' => 'admin/home#index', :as => :admin_home
  namespace :admin do
    resources :categories, :markets, :work_types, :contact_us, :products, :companies, :users, :company_layouts
    resources :albums do
      resources :album_products
    end
    #resources :albums do
     # collection do
      #  get :products
      #end
    #end
  end
  
  namespace :company do
		resources :albums
    namespace :admin do
      resources :contact_us, :products, :companies, :company_layouts
      get '/home' => 'home#index', :as => :home
      resources :company_work_types do
        get :autocomplete_work_type_name, :on => :collection
      end
      resources :albums do
        resources :album_products
      end      
    end
    get '/photos/:type/:id' => 'home#photos', :as => :photos
  end
  
  #get '/albums' => 'company/albums#index', :as => :albums
  
  get '/company_not_found' => 'no_company#company_not_found', :as => :company_not_found
  post '/contact_us_save' => 'home#contact_us_save', :as => :contact_us_save
  
end

app/controllers/company/admin/company_work_types_controller.rb
class Company::Admin::CompanyWorkTypesController < Company::Admin::CompanyAdminApplicationController  
  before_action :set_company_work_type, only: [:show, :edit, :update, :destroy]

  autocomplete :work_type, :name, :full => true

  # GET /company_work_types
  # GET /company_work_types.json
  def index
    @company_work_types = @current_company.company_work_types.order(sort_column(params[:sort]) + " " + sort_direction(params[:direction])).paginate(:per_page => PER_PAGE, :page => params[:page])
  end

  # GET /company_work_types/1
  # GET /company_work_types/1.json
  def show
  end

  # GET /company_work_types/new
  def new
    @company_work_type = CompanyWorkType.new
  end

  # GET /company_work_types/1/edit
  def edit
  end

  # POST /company_work_types
  # POST /company_work_types.json
  def create
    respond_to do |format|
      if params[:work_type_name].present?
        work_type = WorkType.find_or_create_by(name: params[:work_type_name])
        params[:company_work_type][:work_type_id] = work_type.id        
        @company_work_type = CompanyWorkType.new(company_work_type_params)
        if @company_work_type.save
          format.html { redirect_to company_admin_company_work_types_url, notice: 'Company Work Type was successfully created.' }
          format.json { render :show, status: :created, location: @company_work_type }
        else
          format.html { render :new }
          format.json { render json: @company_work_type.errors, status: :unprocessable_entity }
        end
      else
        @company_work_type = CompanyWorkType.new(company_work_type_params)
        format.html { render :new }
        format.json { render json: @company_work_type.errors, status: :unprocessable_entity }        
      end    
    end
  end

  # PATCH/PUT /company_work_types/1
  # PATCH/PUT /company_work_types/1.json
  def update
    respond_to do |format|
      if params[:work_type_name].present?
        work_type = WorkType.find_or_create_by(name: params[:work_type_name])
        params[:company_work_type][:work_type_id] = work_type.id      
        if @company_work_type.update(company_work_type_params)
          format.html { redirect_to company_admin_company_work_types_url, notice: 'Company Work Type was successfully updated.' }
          format.json { render :show, status: :ok, location: @company_work_type }
        else
          format.html { render :edit }
          format.json { render json: @company_work_type.errors, status: :unprocessable_entity }
        end
      else  
        format.html { render :edit }
        format.json { render json: @company_work_type.errors, status: :unprocessable_entity }        
      end  
    end
  end

  # DELETE /company_work_types/1
  # DELETE /company_work_types/1.json
  def destroy
    work_type_id = @company_work_type.work_type_id
    @company_work_type.destroy
    
    #destroy work type if no longer use in company.
    work_type = WorkType.find(work_type_id)
    unless work_type.is_default
      company_work_type = work_type.company_work_types.first
      unless company_work_type
        work_type.destroy
      end
    end
      
    respond_to do |format|
      format.html { redirect_to company_admin_company_work_types_url, notice: 'Company Work Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_work_type
      @company_work_type = CompanyWorkType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_work_type_params
      params.require(:company_work_type).permit!
    end
end

app/views/company/admin/company_work_types/_form.html.erb
<%= form_for [:company_admin, @company_work_type], :html => {:class => "form-horizontal"} do |f| %>
  <% if @company_work_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company_work_type.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @company_work_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.hidden_field :company_id, :value => @current_company.id  %>

  <div class="form-group">
	  	<label class="col-sm-2 control-label">Work Type</label>
	  	<div class="col-sm-10">
	      <%= autocomplete_field_tag 'work_type_name', (@company_work_type.work_type.name if @company_work_type.work_type), autocomplete_work_type_name_company_admin_company_work_types_path,  :class =>"form-control" %>
	    </div>  
			<%#= f.autocomplete_field :work_type_name, autocomplete_work_type_name_company_admin_company_work_types_path %>    
    </div>
    

  <div class="form-group">
  	<div class="col-sm-offset-2 col-sm-10">
  		<%= link_to 'Back', company_admin_company_work_types_path, :class => "btn-primary btn" %>
    	<%= f.submit  :class => "btn-success btn" %>
    </div>	
  </div>
<% end %>

app/views/company/admin/company_work_types/index.html.erb
<h3 class="alert alert-info">Listing work types <div class="right mt3"><%= link_to 'New Work Type', new_company_admin_company_work_type_path, :class => "btn-primary btn" %></div></h3>
<div class="table-responsive">
	<table class="table table-hover table-condensed">
		  <thead>
		    <tr>
		    	<th><%= sortable "name", t("general.name") %></th>
		      <th colspan="3"></th>
		    </tr>
		  </thead>
		
		  <tbody>
		    <% @company_work_types.each do |company_work_type| %>
		      <tr>
		      	<td><%= company_work_type.work_type.name if company_work_type.work_type %></td>
		      	<td><%= link_to 'Edit', edit_company_admin_company_work_type_path(company_work_type), :class => "btn-success btn" %>
		        <%= link_to 'Destroy', [:company_admin, company_work_type], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn-danger btn" %></td>
		      </tr>
		    <% end %>
		  </tbody>
	</table>
			<div class="right"><%= will_paginate @company_work_types %></div>
</div>	