config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :company_layouts
  end

  get '/' => 'company/home#index', :constraints => { :subdomain => /.+/ }
  constraints DomainConstraint.new('textile.com') do
    root :to => 'home#index', :as => :home
  end
  root :to => "company/home#index", :as => :company_home
  
  
  devise_for :users, :controllers => { :sessions => 'sessions', :registrations => 'registrations', :passwords => 'passwords' }
  
  resources :users
  
  get '/admin' => 'admin/home#index', :as => :admin_home
  namespace :admin do
    resources :categories, :markets, :work_types, :contact_us, :products, :companies, :users, :company_layouts
    resources :albums do
      resources :album_products
    end
    #resources :albums do
     # collection do
      #  get :products
      #end
    #end
  end
  
  namespace :company do
		resources :albums
    namespace :admin do
      resources :contact_us, :products, :companies, :company_layouts
      get '/home' => 'home#index', :as => :home
      resources :company_work_types do
        get :autocomplete_work_type_name, :on => :collection
      end
      resources :albums do
        resources :album_products
      end      
    end
    get '/photos/:type/:id' => 'home#photos', :as => :photos
  end
  
  #get '/albums' => 'company/albums#index', :as => :albums
  
  get '/company_not_found' => 'no_company#company_not_found', :as => :company_not_found
  post '/contact_us_save' => 'home#contact_us_save', :as => :contact_us_save
  
end

app/models/album_product.rb
class AlbumProduct < ActiveRecord::Base
  belongs_to :album
  belongs_to :product

  validates_presence_of :album_id, :product_id
  
  validates_uniqueness_of :product_id, :scope => :album_id 
end

app/controllers/admin/album_products_controller.rb
class Admin::AlbumProductsController < Admin::AdminApplicationController  
  before_action :set_album_product, only: [:show, :edit, :update, :destroy]
  
  before_action :set_album

  # GET /admin/album_products
  # GET /admin/album_products.json
  def index
    @album_products = AlbumProduct.order(sort_column(params[:sort]) + " " + sort_direction(params[:direction])).paginate(:per_page => PER_PAGE, :page => params[:page])
    @album_product = AlbumProduct.new
  end

  # GET /admin/album_products/1
  # GET /admin/album_products/1.json
  def show
  end

  # GET /admin/album_products/new
  def new
    @album_product = AlbumProduct.new
  end

  # GET /admin/album_products/1/edit
  def edit
  end

  # POST /admin/album_products
  # POST /admin/album_products.json
  def create
    @album_product = AlbumProduct.new(album_product_params)
    @album_products = AlbumProduct.order(sort_column(params[:sort]) + " " + sort_direction(params[:direction])).paginate(:per_page => PER_PAGE, :page => params[:page])
    respond_to do |format|
      if @album_product.save
        format.html {  render action: 'index', notice: 'Album product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album_product }
      else
        format.html { render action: 'new' }
        format.json { render json: @album_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/album_products/1
  # PATCH/PUT /admin/album_products/1.json
  def update
    respond_to do |format|
      if @album_product.update(album_product_params)
        format.html {  render action: 'edit', notice: 'Album product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/album_products/1
  # DELETE /admin/album_products/1.json
  def destroy
    @album_product.destroy
    respond_to do |format|
      format.html { redirect_to admin_album_album_products_url(@album), notice: 'Album product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album_product
      @album_product = AlbumProduct.find(params[:id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:album_id])
    end    

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_product_params
      params.require(:album_product).permit(:album_id, :product_id)
    end
end

app/controllers/company/admin/album_products_controller.rb
class Company::Admin::AlbumProductsController < Company::Admin::CompanyAdminApplicationController  
  before_action :set_album_product, only: [:show, :edit, :update, :destroy]
  
  before_action :set_album

  # GET /admin/album_products
  # GET /admin/album_products.json
  def index
    @album_products = AlbumProduct.includes(:product, :album).order(sort_column(params[:sort]) + " " + sort_direction(params[:direction])).paginate(:per_page => PER_PAGE, :page => params[:page])
    @album_product = AlbumProduct.new
  end

  # GET /admin/album_products/1
  # GET /admin/album_products/1.json
  def show
  end

  # GET /admin/album_products/new
  def new
    @album_product = AlbumProduct.new
  end

  # GET /admin/album_products/1/edit
  def edit
  end

  # POST /admin/album_products
  # POST /admin/album_products.json
  def create
    @album_product = AlbumProduct.new(album_product_params)
    @album_products = AlbumProduct.includes(:product, :album).order(sort_column(params[:sort]) + " " + sort_direction(params[:direction])).paginate(:per_page => PER_PAGE, :page => params[:page])
    respond_to do |format|
      if @album_product.save
        @album_product = AlbumProduct.new
        format.html {  render action: 'index', notice: 'Album product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album_product }
      else
        format.html { render action: 'index' }
        format.json { render json: @album_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/album_products/1
  # PATCH/PUT /admin/album_products/1.json
  def update
    respond_to do |format|
      if @album_product.update(album_product_params)
        format.html {  render action: 'edit', notice: 'Album product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/album_products/1
  # DELETE /admin/album_products/1.json
  def destroy
    @album_product.destroy
    respond_to do |format|
      format.html { redirect_to company_admin_album_album_products_url(@album), notice: 'Album product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album_product
      @album_product = AlbumProduct.find(params[:id])
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.includes(:company).find(params[:album_id])
    end    

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_product_params
      params.require(:album_product).permit(:album_id, :product_id)
    end
end

app/helpers/admin/album_products_helper.rb
module Admin::AlbumProductsHelper
end

app/views/company/admin/album_products/_form.html.erb
<table class="table">
	<tr>
		<td width="50%">
			<%= form_for([:company_admin, @album, @album_product]) do |f| %>
			  <% if @album_product.errors.any? %>
			    <div id="error_explanation">
			      <h2><%= pluralize(@album_product.errors.count, "error") %> prohibited this album_product from being saved:</h2>
			
			      <ul>
			      <% @album_product.errors.full_messages.each do |msg| %>
			        <li><%= msg %></li>
			      <% end %>
			      </ul>
			    </div>
			  <% end %>
			
					<%= f.hidden_field :album_id, :value => @album.id %>
			   	<div class="field">
			      <%= f.label :product_id %>
						<%= f.select :product_id, options_for_select([["Select", ""]] + Product.active.where(:company_id => @album.company.id).collect {|r| [r.name, r.id]}, (@album_product.product.id unless @album_product.product.nil?)), {}, {:multiple => true}  %>
			   	</div>    
			
			  <div class="actions">
			    <%= f.submit %>
			  </div>
			<% end %>
		</td>
		<td width="50%">
			
			<table class="table">
			  <thead>
			    <tr>
			    	<th><%= t("general.name") %></th>
			    </tr>
			  </thead>
			
			  <tbody>
			    <% @album.products.each do |product| %>
			      <tr>
			      	<td><%= product.name %></td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
			
		</td>	
	</tr>
</table>

app/views/company/admin/album_products/index.html.erb
<h3 class="alert alert-info">Listing Products - <%= @album.name %></h3>
<div class="table-responsive">
	<table class="table table-hover table-condensed">
	<tr>
		<td width="30%">
			<%= form_for [:company_admin, @album, @album_product], :html => {:class => "form-horizontal"} do |f| %>
			  <% if @album_product.errors.any? %>
			    <div id="error_explanation">
			      <ul>
			      <% @album_product.errors.full_messages.each do |msg| %>
			        <li><%= msg %></li>
			      <% end %>
			      </ul>
			    </div>
			  <% end %>
			
				<%= f.hidden_field :album_id, :value => @album.id %>
			  <div class="form-group">
				  	<label class="col-sm-2 control-label">Select Product</label>
				  	<div class="col-sm-10">	
				  		<%= f.select :product_id, options_for_select([["Select", ""]] + Product.active.where(:company_id => @album.company.id).collect {|r| [r.name, r.id]}, (@album_product.product.id unless @album_product.product.nil?)), :class =>"form-control"  %>
				  	</div>	
			   </div>				
		
			  <div class="form-group">
			  	<div class="col-sm-offset-2 col-sm-10">
			  		<%= link_to 'Back', company_admin_albums_path, :class => "btn-primary btn" %>
			    	<%= f.submit  :class => "btn-success btn" %>
			    </div>	
			  </div>
			<% end %>
		</td>
		<td width="70%">
			<% if @album_products.count > 0 %>
				<table class="table table-hover table-condensed">
				  <thead>
				    <tr>
				      <th>Name</th>
				      <th>Code</th>
				      <th>Photo</th>
				    </tr>
				  </thead>
				
				  <tbody>
				    <% @album_products.each do |album_product| %>
				      <tr>
				        <td><%= album_product.product.name %></td>
				        <td><%= album_product.product.code %></td>
				        <td><%= image_tag(album_product.product.photo_url_small, :alt => "photo") %></td>
				        <td><%= link_to 'Destroy', [:company_admin, @album, album_product], method: :delete, data: { confirm: 'Are you sure?' } %></td>
				      </tr>
				    <% end %>
				  </tbody>
				</table>
				<%= will_paginate @album_products %>
			<% else %>	
				<h3 class="alert alert-info">Album is empty...!!</h3>
			<% end %>	
		</td>	
	</tr>
</table>	
</div>			
				

app/views/company/admin/album_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Album:</strong>
  <%= @album_product.album_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @album_product.product_id %>
</p>

<%= link_to 'Edit', edit_company_admin_album_album_product_path(@album, @album_product) %> |
<%= link_to 'Back', company_admin_album_album_products_path(@album) %>