config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :company_layouts
  end

  get '/' => 'company/home#index', :constraints => { :subdomain => /.+/ }
  constraints DomainConstraint.new('textile.com') do
    root :to => 'home#index', :as => :home
  end
  root :to => "company/home#index", :as => :company_home
  
  
  devise_for :users, :controllers => { :sessions => 'sessions', :registrations => 'registrations', :passwords => 'passwords' }
  
  resources :users
  
  get '/admin' => 'admin/home#index', :as => :admin_home
  namespace :admin do
    resources :categories, :markets, :work_types, :contact_us, :products, :companies, :users, :company_layouts
    resources :albums do
      resources :album_products
    end
    #resources :albums do
     # collection do
      #  get :products
      #end
    #end
  end
  
  namespace :company do
		resources :albums
    namespace :admin do
      resources :contact_us, :products, :companies, :company_layouts
      get '/home' => 'home#index', :as => :home
      resources :company_work_types do
        get :autocomplete_work_type_name, :on => :collection
      end
      resources :albums do
        resources :album_products
      end      
    end
    get '/photos/:type/:id' => 'home#photos', :as => :photos
  end
  
  #get '/albums' => 'company/albums#index', :as => :albums
  
  get '/company_not_found' => 'no_company#company_not_found', :as => :company_not_found
  post '/contact_us_save' => 'home#contact_us_save', :as => :contact_us_save
  
end

app/models/market.rb
class Market < ActiveRecord::Base
  has_many :companies
  
  validates_presence_of :name
  
  scope :active, -> {where(:is_active => true)}
end

app/controllers/admin/markets_controller.rb
class Admin::MarketsController < Admin::AdminApplicationController  
  before_action :set_market, only: [:show, :edit, :update, :destroy]

  # GET /markets
  # GET /markets.json
  def index
    @markets = Market.order(sort_column(params[:sort]) + " " + sort_direction(params[:direction])).paginate(:per_page => PER_PAGE, :page => params[:page])
  end

  # GET /markets/1
  # GET /markets/1.json
  def show
  end

  # GET /markets/new
  def new
    @market = Market.new
  end

  # GET /markets/1/edit
  def edit
  end

  # POST /markets
  # POST /markets.json
  def create
    @market = Market.new(market_params)

    respond_to do |format|
      if @market.save
        format.html { redirect_to admin_markets_url, notice: 'Market was successfully created.' }
        format.json { render :show, status: :created, location: @market }
      else
        format.html { render :new }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markets/1
  # PATCH/PUT /markets/1.json
  def update
    respond_to do |format|
      if @market.update(market_params)
        format.html { redirect_to admin_markets_url, notice: 'Market was successfully updated.' }
        format.json { render :show, status: :ok, location: @market }
      else
        format.html { render :edit }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markets/1
  # DELETE /markets/1.json
  def destroy
    @market.destroy
    respond_to do |format|
      format.html { redirect_to admin_markets_url, notice: 'Market was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_market
      @market = Market.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def market_params
      params.require(:market).permit!
    end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/admin/markets/_form.html.erb
<%= form_for [:admin, @market], :html => {:class => "form-horizontal"} do |f| %>
  <% if @market.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@market.errors.count, "error") %> prohibited this market from being saved:</h2>

      <ul>
      <% @market.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
	  	<label class="col-sm-2 control-label">Name</label>
	  	<div class="col-sm-10"><%= f.text_field :name, :class =>"form-control", :placeholder => "Name" %></div>	
   </div>
  <div class="form-group">
	  	<label class="col-sm-2 control-label">Description</label>
	  	<div class="col-sm-10"><%= f.text_field :description, :class =>"form-control", :placeholder => "Description" %></div>	
   </div>
    
  <div class="form-group">
	  	<label class="col-sm-2 control-label">Address</label>
	  	<div class="col-sm-10"><%= f.text_field :address, :class =>"form-control", :placeholder => "Address" %></div>	
   </div>
   
  <div class="form-group">
	  	<label class="col-sm-2 control-label">City</label>
	  	<div class="col-sm-10"><%= f.text_field :city, :class =>"form-control", :placeholder => "City" %></div>	
   </div>
  <div class="form-group">
	  	<label class="col-sm-2 control-label">Area</label>
	  	<div class="col-sm-10"><%= f.text_field :area, :class =>"form-control", :placeholder => "Area" %></div>	
   </div>
  <div class="form-group">
	  	<label class="col-sm-2 control-label">Pincode</label>
	  	<div class="col-sm-10"><%= f.text_field :pincode, :class =>"form-control", :placeholder => "Pincode" %></div>	
   </div>
  <div class="form-group">
	  	<label class="col-sm-2 control-label">Latitude</label>
	  	<div class="col-sm-10"><%= f.text_field :latitude, :class =>"form-control", :placeholder => "Latitude" %></div>	
   </div>
  <div class="form-group">
	  	<label class="col-sm-2 control-label">Longitude</label>
	  	<div class="col-sm-10"><%= f.text_field :longitude, :class =>"form-control", :placeholder => "Longitude" %></div>	
   </div>               
    
   <div class="checkbox">
      <label class="col-sm-2 control-label"></label>
      <label><%= f.check_box :is_active %> Active</label>
   </div>   

  <div class="form-group">
  	<div class="col-sm-offset-2 col-sm-10">
  		<%= link_to 'Back', admin_markets_path, :class => "btn-primary btn" %>
    	<%= f.submit  :class => "btn-success btn" %>
    </div>	
  </div>
<% end %>

app/views/admin/markets/edit.html.erb
<h3 class="alert alert-info">Edit</h3>

<%= render 'form' %>

app/views/admin/markets/index.html.erb
<h3 class="alert alert-info">Listing markets <div class="right mt3"><%= link_to 'New Market', new_admin_market_path, :class => "btn-primary btn" %></div></h3>
<div class="table-responsive">
	<table class="table table-hover table-condensed">
  <thead>
    <tr>
    	<th><%= sortable "name", t("general.name") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @markets.each do |market| %>
      <tr>
      	<td><%= market.name %></td>
        <td><%= link_to 'Edit', edit_admin_market_path(market), :class => "btn-success btn" %>
        <%= link_to 'Destroy', [:admin, market], method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn-danger btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="right"><%= will_paginate @markets %></div>
</div>

app/views/admin/markets/new.html.erb
<h3 class="alert alert-info">Add</h3>

<%= render 'form' %>